# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


_target_: pytorch_lightning.Trainer


accelerator: cpu
devices: "auto"
min_epochs: 200 # Force training for at least these many epochs.
max_epochs: 1000 # 1_000_000

val_check_interval: 1.0 # if 1.0, only check validation set once per training epoch, 0.25, 4 times, 1000, every 1000 batches.

enable_model_summary: null

gradient_clip_val: 0.1

    
log_every_n_steps: 5 # How often to log within steps.
num_sanity_val_steps: 10 # Sanity check runs n validation batches before starting the training routine. 

profiler: "simple" # "simple", "pytorch"
