run:
  dir: logs/debug/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: logs/debug/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"

