run:
  dir: ../scratch/logs/runs/${now:%Y-%m-%d-%H-%M-%S}---${run_name}

sweep:
  dir: ../scratch/logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  # subdir: ${hydra.job.num}
  subdir: ${hydra.job.override_dirname}

job:
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"
