# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

run:
  dir: ../scratch/logs/evaluation/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ../scratch/logs/evaluation/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # subdir: ${hydra.job.num}
  subdir: ${hydra.job.override_dirname}

job:
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"

