run:
  dir: ../scratch/logs/evaluation/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ../scratch/logs/evaluation/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # subdir: ${hydra.job.num}
  subdir: ${hydra.job.override_dirname}

job:
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"

