# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

run:
  dir: ../scratch/logs/training/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # dir: scratch/logs/training/runs/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ../scratch/logs/training/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # dir: scratch/logs/training/multiruns/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  # subdir: ${hydra.job.num}
  subdir: ${hydra.job.override_dirname}

job:
  chdir: True
  env_set:
    CUDA_DEVICE_ORDER: "PCI_BUS_ID"
    HYDRA_FULL_ERROR: "1"
  config:
    override_dirname:
      exclude_keys:
        - ckpt_path
        - run_path
        - datamodule
        - datamodule.batch_size
        - datamodule.dataset
        - datamodule.dataset.correlated_z
        - datamodule.dataset.corr_prob
        - datamodule.dataset.linear
        - datamodule.dataset.non_linearity
        - datamodule.dataset.num_domains
        - datamodule.dataset.x_dim
        - logger.wandb.tags
        - model.optimizer
        - model.z_dim
        - model.optimizer.lr
        - model.penalty_criterion
        - model.penalty_criterion.minmax
        - model.penalty_criterion.mmd
        - model.pl_model_ckpt_path
        - model.additional_logger.logging_interval
        - model.save_encoded_data
        - model.linear_steps
        - model.wait_steps
        - model/optimizer
        - model/scheduler_config
        - model.scheduler_config.scheduler_dict.monitor
        # - model
        - callbacks
        - callbacks.model_checkpoint.monitor
        - callbacks.early_stopping
        - callbacks.visualization_callback
        - trainer.max_epochs
        - trainer.accelerator
        - trainer.devices
        # - model.optimizer.lr
        # - model.z_dim=5

