# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

defaults:
  - _self_
  - trainer: default.yaml
  - model: default_ckpt.yaml
  - datamodule: mnist.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: wandb # set to null if you don't want to use any loggers
  - hydra: evaluation


  # debugging config (enable through command line, e.g. `python train.py debug=fast)
  - debug: null

  # enable color logging
  # - override hydra/hydra_logging: colorlog
  # - override hydra/job_logging: colorlog
  # enable job submission through slurm
  # options: submitit_slurm_mila, submitit_slurm_mila_v100_multicore
  # , submitit_slurm_mila_a100, submitit_slurm_narval, submitit_slurm_narval_multicore
  # , submitit_local_
  # - override hydra/launcher: submitit_slurm_narval # options: submitit_slurm_mila, submitit_slurm_mila_v100_multicore, submitit_slurm_narval, submitit_slurm_narval_multicore, submitit_local_

model:
  checkpoint_path: ${ckpt_path}
  write_testing_output: True

work_dir: ${hydra:runtime.cwd} # /home/aminm/mechanism-based-disentanglement/disentanglement_by_mechanisms # ${hydra:runtime.cwd}

print_config: True

ignore_warnings: True

seed: 1234

run_name: ${model.logging_name} # Will be used for logging

