# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 120 # 24 hrs
cpus_per_task: 4
gpus_per_node: null
# gres: gpu:1
tasks_per_node: 1
mem_gb: 40
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: long
# comment: null
# constraint: null
# exclude: null
# cpus_per_gpu: null
# gpus_per_task: null
# mem_per_gpu: null
# mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
# additional_parameters: {}
array_parallelism: 256
  
setup: # A list of commands to run in sbatch befure running srun
#   - "export LD_PRELOAD=/value"
#     - module unload anaconda
# #     - conda init bash
#     - module load miniconda/3
#     - conda activate bb # ../../../../../scratch-new/.conda/envs/bb/bin/ # bb
#     - export WANDB_API_KEY=1406ef3255ef2806f2ecc925a5e845e7164b5eef
#     - wandb login