# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


_target_: datamodule.base_datamodule.BaseDataModule

defaults:
  - dataset: synthetic_mixing
  
dataset_name: synthetic_mixing
datamodule_name: ${datamodule.dataset.dataset_name}

save_dataset: True
load_dataset: False
data_dir: ${work_dir} # "/home/mila/s/sayed.mansouri-tehrani/scratch/poly_mixing/"
data_dir_narval: ${work_dir} # "/home/aminm/scratch/poly_mixing/"

seed: ${seed}

transform:
    augs: [] # choices=["shift", "hflip", "vflip", "scale", "rotate"]

batch_size: 512
num_workers: 6
shuffle: False
drop_last: False

num_samples:
    train: 12000 # 30000
    valid: 2000 # 4000
    test: 2000

   
transforms:
