# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


_target_: datamodule.encoded_datamodule.EncodedDataModule

defaults:
  - dataset: md_mnist_encoded # mnist, multi_domain_mnist

dataset_name: mnist_encoded
datamodule_name: ${datamodule.dataset_name}

data_dir: ${run_path}

seed: ${seed}
num_domains: ${retrieve_num_domain:${run_path}}
x_dim: ${retrieve_x_dimension:${run_path}}

batch_size: 256
num_workers: 6
shuffle: False
drop_last: False
