

defaults:
  - override /hydra: debug

num_steps: 100
num_validation_runs: 1

trainer:
  max_steps: ${num_steps}
  track_grad_norm: 2 # track gradient norm with loggers
  val_check_interval: ${floor_div:${num_steps}, ${num_validation_runs}}
  #  Available in newer version of PL
  #  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

hydra:
  verbose: True

print_config: False